// Mapeamento oficial de municÃ­pios para CREs fornecido pelo solicitante
const MUNICIPALITY_CRE_MAP = {
  'Abdon Batista': 'Campos Novos',
  'Abelardo Luz': 'XanxerÃª',
  XanxerÃª: 'XanxerÃª',
  'AgrolÃ¢ndia': 'Rio do Sul',
  AgronÃ´mica: 'Rio do Sul',
  'Ãgua Doce': 'JoaÃ§aba',
  'JoaÃ§aba': 'JoaÃ§aba',
  'Ãguas de ChapecÃ³': 'Palmitos',
  'Ãguas Frias': 'ChapecÃ³',
  'Ãguas Mornas': 'FlorianÃ³polis',
  'Alfredo Wagner': 'Ituporanga',
  Ituporanga: 'Ituporanga',
  'Alto Bela Vista': 'ConcÃ³rdia',
  ConcÃ³rdia: 'ConcÃ³rdia',
  Anchieta: 'DionÃ­sio Cerqueira',
  'DionÃ­sio Cerqueira': 'DionÃ­sio Cerqueira',
  Angelina: 'FlorianÃ³polis',
  'Anita Garibaldi': 'Lages',
  AnitÃ¡polis: 'FlorianÃ³polis',
  'AntÃ´nio Carlos': 'FlorianÃ³polis',
  ApiÃºna: 'Ibirama',
  ArabutÃ£: 'Seara',
  Araquari: 'Joinville',
  Joinville: 'Joinville',
  'BraÃ§o do Norte': 'BraÃ§o do Norte',
  ArmazÃ©m: 'BraÃ§o do Norte',
  'AraranguÃ¡': 'AraranguÃ¡',
  'Arroio Trinta': 'Videira',
  Videira: 'Videira',
  Arvoredo: 'Seara',
  Ascurra: 'TimbÃ³',
  TimbÃ³: 'TimbÃ³',
  Atalanta: 'Ituporanga',
  Aurora: 'Ituporanga',
  'BalneÃ¡rio Arroio do Silva': 'AraranguÃ¡',
  'BalneÃ¡rio Barra do Sul': 'Joinville',
  'BalneÃ¡rio CamboriÃº': 'ItajaÃ­',
  ItajaÃ­: 'ItajaÃ­',
  'BalneÃ¡rio Gaivota': 'AraranguÃ¡',
  'BalneÃ¡rio PiÃ§arras': 'ItajaÃ­',
  'BalneÃ¡rio RincÃ£o': 'CriciÃºma',
  CriciÃºma: 'CriciÃºma',
  Bandeirante: "SÃ£o Miguel d'Oeste",
  'SÃ£o Miguel do Oeste': "SÃ£o Miguel d'Oeste",
  'Barra Bonita': "SÃ£o Miguel d'Oeste",
  'Barra Velha': 'Joinville',
  'Bela Vista do Toldo': 'Canoinhas',
  Canoinhas: 'Canoinhas',
  Belmonte: "SÃ£o Miguel d'Oeste",
  'Benedito Novo': 'TimbÃ³',
  BiguaÃ§u: 'FlorianÃ³polis',
  'Bocaina do Sul': 'Lages',
  Lages: 'Lages',
  'Bom Jardim da Serra': 'SÃ£o Joaquim',
  'SÃ£o Joaquim': 'SÃ£o Joaquim',
  'Bom Jesus': 'XanxerÃª',
  'Bom Jesus do Oeste': 'Maravilha',
  Maravilha: 'Maravilha',
  'Bom Retiro': 'SÃ£o Joaquim',
  Bombinhas: 'ItajaÃ­',
  'Brusque': 'Brusque',
  BotuverÃ¡: 'Brusque',
  'BraÃ§o do Trombudo': 'Rio do Sul',
  'Rio do Sul': 'Rio do Sul',
  BrunÃ³polis: 'Campos Novos',
  'Campos Novos': 'Campos Novos',
  Caibi: 'Palmitos',
  Palmitos: 'Palmitos',
  Calmon: 'CaÃ§ador',
  'CaÃ§ador': 'CaÃ§ador',
  CamboriÃº: 'ItajaÃ­',
  'Campo Alegre': 'Mafra',
  Mafra: 'Mafra',
  'Campo Belo do Sul': 'Lages',
  'Campo ErÃª': "SÃ£o LourenÃ§o d'Oeste",
  'SÃ£o LourenÃ§o do Oeste': "SÃ£o LourenÃ§o d'Oeste",
  Canelinha: 'Brusque',
  'CapÃ£o Alto': 'Lages',
  Capinzal: 'JoaÃ§aba',
  'Capivari de Baixo': 'TubarÃ£o',
  'TubarÃ£o': 'TubarÃ£o',
  Catanduvas: 'JoaÃ§aba',
  'Caxambu do Sul': 'ChapecÃ³',
  ChapecÃ³: 'ChapecÃ³',
  'Celso Ramos': 'Campos Novos',
  'Cerro Negro': 'Lages',
  'ChapadÃ£o do Lageado': 'Ituporanga',
  'Cocal do Sul': 'CriciÃºma',
  'Cordilheira Alta': 'ChapecÃ³',
  'Coronel Freitas': 'ChapecÃ³',
  'Coronel Martins': "SÃ£o LourenÃ§o d'Oeste",
  'Correia Pinto': 'Lages',
  CorupÃ¡: 'JaraguÃ¡ do Sul',
  'JaraguÃ¡ do Sul': 'JaraguÃ¡ do Sul',
  'Cunha PorÃ£': 'Palmitos',
  CunhataÃ­: 'Palmitos',
  Descanso: "SÃ£o Miguel d'Oeste",
  'Dona Emma': 'Ibirama',
  Ibirama: 'Ibirama',
  'Doutor Pedrinho': 'TimbÃ³',
  'Entre Rios': 'XanxerÃª',
  Ermo: 'AraranguÃ¡',
  'Erval Velho': 'JoaÃ§aba',
  'Faxinal dos Guedes': 'XanxerÃª',
  'Flor do SertÃ£o': 'Maravilha',
  FlorianÃ³polis: 'FlorianÃ³polis',
  'Formosa do Sul': 'Quilombo',
  'Forquilhinha': 'CriciÃºma',
  Fraiburgo: 'Videira',
  'Frei RogÃ©rio': 'Curitibanos',
  Curitibanos: 'Curitibanos',
  GalvÃ£o: "SÃ£o LourenÃ§o d'Oeste",
  Laguna: 'Laguna',
  Garopaba: 'Laguna',
  Garuva: 'Joinville',
  Blumenau: 'Blumenau',
  Gaspar: 'Blumenau',
  'Governador Celso Ramos': 'FlorianÃ³polis',
  'GrÃ£o ParÃ¡': 'BraÃ§o do Norte',
  Gravatal: 'TubarÃ£o',
  Guabiruba: 'Brusque',
  Guaraciaba: "SÃ£o Miguel d'Oeste",
  Guaramirim: 'JaraguÃ¡ do Sul',
  "GuarujÃ¡ do Sul": 'DionÃ­sio Cerqueira',
  Guatambu: 'ChapecÃ³',
  'GuatambÃº': 'ChapecÃ³',
  "Herval d'Oeste": 'JoaÃ§aba',
  Ibiam: 'Campos Novos',
  IbicarÃ©: 'JoaÃ§aba',
  IÃ§ara: 'CriciÃºma',
  Ilhota: 'Blumenau',
  ImaruÃ­: 'Laguna',
  Imbituba: 'Laguna',
  Imbuia: 'Ituporanga',
  Indaial: 'TimbÃ³',
  IomerÃª: 'Videira',
  Ipira: 'ConcÃ³rdia',
  "IporÃ£ do Oeste": 'Itapiranga',
  Itapiranga: 'Itapiranga',
  IpuaÃ§u: 'XanxerÃª',
  Ipumirim: 'Seara',
  Iraceminha: 'Maravilha',
  Irani: 'ConcÃ³rdia',
  Irati: 'Quilombo',
  Quilombo: 'Quilombo',
  IrineÃ³polis: 'Canoinhas',
  ItÃ¡: 'Seara',
  ItaiÃ³polis: 'Mafra',
  Itapema: 'ItajaÃ­',
  ItapoÃ¡: 'Joinville',
  JaborÃ¡: 'JoaÃ§aba',
  'Jacinto Machado': 'AraranguÃ¡',
  Jaguaruna: 'TubarÃ£o',
  JardinÃ³polis: 'Quilombo',
  'JosÃ© Boiteux': 'Ibirama',
  JupiÃ¡: "SÃ£o LourenÃ§o d'Oeste",
  LacerdÃ³polis: 'JoaÃ§aba',
  'Lajeado Grande': 'XanxerÃª',
  Laurentino: 'Rio do Sul',
  'Lauro MÃ¼ller': 'CriciÃºma',
  'Lauro Muller': 'CriciÃºma',
  'Lebon RÃ©gis': 'CaÃ§ador',
  'Leoberto Leal': 'Ituporanga',
  'LindÃ³ia do Sul': 'Seara',
  Lontras: 'Ibirama',
  'Luiz Alves': 'Blumenau',
  Luzerna: 'JoaÃ§aba',
  Macieira: 'CaÃ§ador',
  'Major Gercino': 'Brusque',
  'Major Vieira': 'Canoinhas',
  MaracajÃ¡: 'AraranguÃ¡',
  Marema: 'XanxerÃª',
  Massaranduba: 'JaraguÃ¡ do Sul',
  'Matos Costa': 'CaÃ§ador',
  Meleiro: 'AraranguÃ¡',
  'Mirim Doce': 'TaiÃ³',
  'TaiÃ³': 'TaiÃ³',
  Modelo: 'Maravilha',
  Mondai: 'Palmitos',
  'MondaÃ­': 'Palmitos',
  'Monte Carlo': 'Campos Novos',
  'Monte Castelo': 'Mafra',
  'Morro do FumaÃ§a': 'CriciÃºma',
  'Morro da FumaÃ§a': 'CriciÃºma',
  'Morro Grande': 'AraranguÃ¡',
  Navegantes: 'ItajaÃ­',
  'Nova Erechim': 'ChapecÃ³',
  'Nova Itaberaba': 'ChapecÃ³',
  'Nova Trento': 'Brusque',
  'Nova Veneza': 'CriciÃºma',
  'Novo Horizonte': "SÃ£o LourenÃ§o d'Oeste",
  Orleans: 'CriciÃºma',
  'OtacÃ­lio Costa': 'Lages',
  Ouro: 'JoaÃ§aba',
  'Ouro Verde': 'XanxerÃª',
  Painel: 'Lages',
  PalhoÃ§a: 'FlorianÃ³polis',
  'Palma Sola': 'DionÃ­sio Cerqueira',
  Palmeira: 'Lages',
  Papanduva: 'Mafra',
  ParaÃ­so: "SÃ£o Miguel d'Oeste",
  'Passo de Torres': 'AraranguÃ¡',
  'Passos Maia': 'XanxerÃª',
  'Paulo Lopes': 'Laguna',
  'Pedras Grandes': 'TubarÃ£o',
  Penha: 'ItajaÃ­',
  Peritiba: 'ConcÃ³rdia',
  'Pescaria Brava': 'Laguna',
  PetrolÃ¢ndia: 'Ituporanga',
  Pinhalzinho: 'Maravilha',
  'Pinheiro Preto': 'Videira',
  Piratuba: 'ConcÃ³rdia',
  'Planalto Alegre': 'ChapecÃ³',
  Pomerode: 'Blumenau',
  'Ponte Alta': 'Lages',
  'Ponte Alta do Norte': 'Curitibanos',
  'Ponte Serrada': 'XanxerÃª',
  'Porto Belo': 'ItajaÃ­',
  'Porto UniÃ£o': 'Canoinhas',
  'Pouso Redondo': 'TaiÃ³',
  'Praia Grande': 'AraranguÃ¡',
  Paial: 'Seara',
  'Presidente Castello Branco': 'ConcÃ³rdia',
  'Presidente GetÃºlio': 'Ibirama',
  'Presidente Nereu': 'Ibirama',
  Princesa: 'DionÃ­sio Cerqueira',
  'Rancho Queimado': 'FlorianÃ³polis',
  'Rio das Antas': 'CaÃ§ador',
  'Rio do Campo': 'TaiÃ³',
  'Rio do Oeste': 'Rio do Sul',
  'Rio dos Cedros': 'TimbÃ³',
  'Rio Fortuna': 'BraÃ§o do Norte',
  'Rio Negrinho': 'Mafra',
  'Rio Rufino': 'SÃ£o Joaquim',
  Riqueza: 'Palmitos',
  Rodeio: 'TimbÃ³',
  RomelÃ¢ndia: 'Maravilha',
  Salete: 'TaiÃ³',
  Saltinho: 'Maravilha',
  'Salto Veloso': 'Videira',
  SangÃ£o: 'TubarÃ£o',
  'Santa CecÃ­lia': 'Curitibanos',
  'Santa Helena': 'Itapiranga',
  'Santa Rosa de Lima': 'BraÃ§o do Norte',
  'Santa Rosa do Sul': 'AraranguÃ¡',
  'Santa Terezinha': 'TaiÃ³',
  'Santa Terezinha do Progresso': 'Maravilha',
  'Santiago do Sul': 'Quilombo',
  'Santo Amaro da Imperatriz': 'FlorianÃ³polis',
  'SÃ£o Bento do Sul': 'Mafra',
  'SÃ£o Bernardino': "SÃ£o LourenÃ§o d'Oeste",
  'SÃ£o BonifÃ¡cio': 'FlorianÃ³polis',
  'SÃ£o Carlos': 'Palmitos',
  'SÃ£o CristÃ³vÃ£o do Sul': 'Curitibanos',
  'SÃ£o CristovÃ£o do Sul': 'Curitibanos',
  'SÃ£o Domingos': 'XanxerÃª',
  'SÃ£o Francisco do Sul': 'Joinville',
  'SÃ£o JoÃ£o Batista': 'Brusque',
  'SÃ£o JoÃ£o do ItaperiÃº': 'Joinville',
  'SÃ£o JoÃ£o do Oeste': 'Itapiranga',
  'SÃ£o JoÃ£o do Sul': 'AraranguÃ¡',
  'SÃ£o JosÃ©': 'FlorianÃ³polis',
  'SÃ£o JosÃ© do Cedro': 'DionÃ­sio Cerqueira',
  'SÃ£o JosÃ© do Cerrito': 'Lages',
  'SÃ£o Ludgero': 'BraÃ§o do Norte',
  'SÃ£o Martinho': 'BraÃ§o do Norte',
  'SÃ£o Miguel da Boa Vista': 'Maravilha',
  'SÃ£o Pedro de AlcÃ¢ntara': 'FlorianÃ³polis',
  Saudades: 'Maravilha',
  Schroeder: 'JaraguÃ¡ do Sul',
  Seara: 'Seara',
  'Serra Alta': 'Maravilha',
  SiderÃ³polis: 'CriciÃºma',
  Sombrio: 'AraranguÃ¡',
  'Sul Brasil': 'Maravilha',
  'TangarÃ¡': 'Videira',
  Tigrinhos: 'Maravilha',
  Tijucas: 'Brusque',
  'TimbÃ© do Sul': 'AraranguÃ¡',
  'TimbÃ³ Grande': 'CaÃ§ador',
  'TrÃªs Barras': 'Canoinhas',
  Treviso: 'CriciÃºma',
  'Treze de Maio': 'TubarÃ£o',
  'Treze TÃ­lias': 'JoaÃ§aba',
  'Trombudo Central': 'Rio do Sul',
  TunÃ¡polis: 'Itapiranga',
  Turvo: 'AraranguÃ¡',
  'UniÃ£o do Oeste': 'Quilombo',
  Urubici: 'SÃ£o Joaquim',
  Urupema: 'SÃ£o Joaquim',
  Urussanga: 'CriciÃºma',
  VargeÃ£o: 'XanxerÃª',
  Vargem: 'Campos Novos',
  'Vargem Bonita': 'JoaÃ§aba',
  'Vidal Ramos': 'Ituporanga',
  'Vitor Meirelles': 'Ibirama',
  'Vitor Meireles': 'Ibirama',
  Witmarsum: 'Ibirama',
  Xavantina: 'Seara',
  Xaxim: 'XanxerÃª',
  ZortÃ©a: 'Campos Novos'
};

const CRE_NAMES = Array.from(new Set(Object.values(MUNICIPALITY_CRE_MAP))).sort((a, b) =>
  a.localeCompare(b, 'pt-BR')
);

const CRE_NUMBERS = {
  "AraranguÃ¡": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 7,
    presencial: 0,
    online: 1
  },
  "Blumenau": {
    publicoEE: 2756,
    escolas: 46,
    escolasAEE: 26,
    estudantesAEE: 640,
    participantes: 222,
    presencial: 1,
    online: 3
  },
  "BraÃ§o do Norte": {
    publicoEE: 827,
    escolas: 21,
    escolasAEE: 12,
    estudantesAEE: 266,
    participantes: 315,
    presencial: 1,
    online: 2
  },
  "Brusque": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 37,
    presencial: 0,
    online: 2
  },
  "Campos Novos": {
    publicoEE: 530,
    escolas: 22,
    escolasAEE: 7,
    estudantesAEE: 106,
    participantes: 134,
    presencial: 1,
    online: 0
  },
  "Canoinhas": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "CaÃ§ador": {
    publicoEE: 920,
    escolas: 25,
    escolasAEE: 15,
    estudantesAEE: 272,
    participantes: 198,
    presencial: 1,
    online: 1
  },
  "ChapecÃ³": {
    publicoEE: 2003,
    escolas: 43,
    escolasAEE: 36,
    estudantesAEE: 894,
    participantes: 302,
    presencial: 1,
    online: 0
  },
  "ConcÃ³rdia": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 5,
    presencial: 0,
    online: 0
  },
  "CriciÃºma": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Curitibanos": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "DionÃ­sio Cerqueira": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 5,
    presencial: 0,
    online: 1
  },
  "FlorianÃ³polis": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 131,
    presencial: 0,
    online: 14
  },
  "Ibirama": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 47,
    presencial: 0,
    online: 5
  },
  "ItajaÃ­": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Itapiranga": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 17,
    presencial: 0,
    online: 2
  },
  "Ituporanga": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 11,
    presencial: 0,
    online: 2
  },
  "JaraguÃ¡ do Sul": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "JoaÃ§aba": {
    publicoEE: 444,
    escolas: 28,
    escolasAEE: 13,
    estudantesAEE: 181,
    participantes: 143,
    presencial: 1,
    online: 0
  },
  "Joinville": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Lages": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Laguna": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 23,
    presencial: 0,
    online: 2
  },
  "Mafra": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 7,
    presencial: 0,
    online: 3
  },
  "Maravilha": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Palmitos": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Quilombo": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Rio do Sul": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Seara": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 7,
    presencial: 0,
    online: 1
  },
  "SÃ£o Joaquim": {
    publicoEE: 484,
    escolas: 16,
    escolasAEE: 6,
    estudantesAEE: 134,
    participantes: 175,
    presencial: 1,
    online: 4
  },
  "SÃ£o LourenÃ§o d'Oeste": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "SÃ£o Miguel d'Oeste": {
    publicoEE: 423,
    escolas: 23,
    escolasAEE: 11,
    estudantesAEE: 129,
    participantes: 300,
    presencial: 1,
    online: 0
  },
  "TaiÃ³": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "TimbÃ³": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 11,
    presencial: 0,
    online: 2
  },
  "TubarÃ£o": {
    publicoEE: 2050,
    escolas: 43,
    escolasAEE: 31,
    estudantesAEE: 655,
    participantes: 147,
    presencial: 1,
    online: 1
  },
  "Videira": {
    publicoEE: 536,
    escolas: 23,
    escolasAEE: 15,
    estudantesAEE: 202,
    participantes: 152,
    presencial: 1,
    online: 6
  },
  "XanxerÃª": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 13,
    presencial: 0,
    online: 1
  }
};

function generateDefaultCreData(names = CRE_NAMES) {
  return names.map((name, index) => {
    const row = CRE_NUMBERS[name] || {};
    const publicoEE = Number.isFinite(row.publicoEE) ? row.publicoEE : 400 + index * 15;
    const escolas = Number.isFinite(row.escolas) ? row.escolas : 45 + (index % 6) * 3;
    const escolasAEE = Number.isFinite(row.escolasAEE) ? row.escolasAEE : Math.max(10, escolas - 8 - (index % 4));
    const estudantesAEE = Number.isFinite(row.estudantesAEE) ? row.estudantesAEE : Math.round(publicoEE * 0.58) + (index % 10) * 6;
    const participantes = Number.isFinite(row.participantes) ? row.participantes : 120 + (index * 7) % 90;
    const presencial = Number.isFinite(row.presencial) ? row.presencial : 20 + (index % 5) * 5;
    const online = Number.isFinite(row.online) ? row.online : 15 + (index % 7) * 4;
    return {
      code: `CRE${String(index + 1).padStart(2, '0')}`,
      name: `CRE ${name}`,
      regionName: name,
      colorIndex: index,
      publicoEE,
      escolas,
      escolasAEE,
      estudantesAEE,
      participantes,
      presencial,
      online,
      hasAssessoria: (presencial + online) > 0
    };
  });
}

const DEFAULT_CRE_DATA = generateDefaultCreData();
