// Mapeamento oficial de municípios para CREs fornecido pelo solicitante
const MUNICIPALITY_CRE_MAP = {
  'Abdon Batista': 'Campos Novos',
  'Abelardo Luz': 'Xanxerê',
  Xanxerê: 'Xanxerê',
  'Agrolândia': 'Rio do Sul',
  Agronômica: 'Rio do Sul',
  'Água Doce': 'Joaçaba',
  'Joaçaba': 'Joaçaba',
  'Águas de Chapecó': 'Palmitos',
  'Águas Frias': 'Chapecó',
  'Águas Mornas': 'Florianópolis',
  'Alfredo Wagner': 'Ituporanga',
  Ituporanga: 'Ituporanga',
  'Alto Bela Vista': 'Concórdia',
  Concórdia: 'Concórdia',
  Anchieta: 'Dionísio Cerqueira',
  'Dionísio Cerqueira': 'Dionísio Cerqueira',
  Angelina: 'Florianópolis',
  'Anita Garibaldi': 'Lages',
  Anitápolis: 'Florianópolis',
  'Antônio Carlos': 'Florianópolis',
  Apiúna: 'Ibirama',
  Arabutã: 'Seara',
  Araquari: 'Joinville',
  Joinville: 'Joinville',
  'Braço do Norte': 'Braço do Norte',
  Armazém: 'Braço do Norte',
  'Araranguá': 'Araranguá',
  'Arroio Trinta': 'Videira',
  Videira: 'Videira',
  Arvoredo: 'Seara',
  Ascurra: 'Timbó',
  Timbó: 'Timbó',
  Atalanta: 'Ituporanga',
  Aurora: 'Ituporanga',
  'Balneário Arroio do Silva': 'Araranguá',
  'Balneário Barra do Sul': 'Joinville',
  'Balneário Camboriú': 'Itajaí',
  Itajaí: 'Itajaí',
  'Balneário Gaivota': 'Araranguá',
  'Balneário Piçarras': 'Itajaí',
  'Balneário Rincão': 'Criciúma',
  Criciúma: 'Criciúma',
  Bandeirante: "São Miguel d'Oeste",
  'São Miguel do Oeste': "São Miguel d'Oeste",
  'Barra Bonita': "São Miguel d'Oeste",
  'Barra Velha': 'Joinville',
  'Bela Vista do Toldo': 'Canoinhas',
  Canoinhas: 'Canoinhas',
  Belmonte: "São Miguel d'Oeste",
  'Benedito Novo': 'Timbó',
  Biguaçu: 'Florianópolis',
  'Bocaina do Sul': 'Lages',
  Lages: 'Lages',
  'Bom Jardim da Serra': 'São Joaquim',
  'São Joaquim': 'São Joaquim',
  'Bom Jesus': 'Xanxerê',
  'Bom Jesus do Oeste': 'Maravilha',
  Maravilha: 'Maravilha',
  'Bom Retiro': 'São Joaquim',
  Bombinhas: 'Itajaí',
  'Brusque': 'Brusque',
  Botuverá: 'Brusque',
  'Braço do Trombudo': 'Rio do Sul',
  'Rio do Sul': 'Rio do Sul',
  Brunópolis: 'Campos Novos',
  'Campos Novos': 'Campos Novos',
  Caibi: 'Palmitos',
  Palmitos: 'Palmitos',
  Calmon: 'Caçador',
  'Caçador': 'Caçador',
  Camboriú: 'Itajaí',
  'Campo Alegre': 'Mafra',
  Mafra: 'Mafra',
  'Campo Belo do Sul': 'Lages',
  'Campo Erê': "São Lourenço d'Oeste",
  'São Lourenço do Oeste': "São Lourenço d'Oeste",
  Canelinha: 'Brusque',
  'Capão Alto': 'Lages',
  Capinzal: 'Joaçaba',
  'Capivari de Baixo': 'Tubarão',
  'Tubarão': 'Tubarão',
  Catanduvas: 'Joaçaba',
  'Caxambu do Sul': 'Chapecó',
  Chapecó: 'Chapecó',
  'Celso Ramos': 'Campos Novos',
  'Cerro Negro': 'Lages',
  'Chapadão do Lageado': 'Ituporanga',
  'Cocal do Sul': 'Criciúma',
  'Cordilheira Alta': 'Chapecó',
  'Coronel Freitas': 'Chapecó',
  'Coronel Martins': "São Lourenço d'Oeste",
  'Correia Pinto': 'Lages',
  Corupá: 'Jaraguá do Sul',
  'Jaraguá do Sul': 'Jaraguá do Sul',
  'Cunha Porã': 'Palmitos',
  Cunhataí: 'Palmitos',
  Descanso: "São Miguel d'Oeste",
  'Dona Emma': 'Ibirama',
  Ibirama: 'Ibirama',
  'Doutor Pedrinho': 'Timbó',
  'Entre Rios': 'Xanxerê',
  Ermo: 'Araranguá',
  'Erval Velho': 'Joaçaba',
  'Faxinal dos Guedes': 'Xanxerê',
  'Flor do Sertão': 'Maravilha',
  Florianópolis: 'Florianópolis',
  'Formosa do Sul': 'Quilombo',
  'Forquilhinha': 'Criciúma',
  Fraiburgo: 'Videira',
  'Frei Rogério': 'Curitibanos',
  Curitibanos: 'Curitibanos',
  Galvão: "São Lourenço d'Oeste",
  Laguna: 'Laguna',
  Garopaba: 'Laguna',
  Garuva: 'Joinville',
  Blumenau: 'Blumenau',
  Gaspar: 'Blumenau',
  'Governador Celso Ramos': 'Florianópolis',
  'Grão Pará': 'Braço do Norte',
  Gravatal: 'Tubarão',
  Guabiruba: 'Brusque',
  Guaraciaba: "São Miguel d'Oeste",
  Guaramirim: 'Jaraguá do Sul',
  "Guarujá do Sul": 'Dionísio Cerqueira',
  Guatambu: 'Chapecó',
  'Guatambú': 'Chapecó',
  "Herval d'Oeste": 'Joaçaba',
  Ibiam: 'Campos Novos',
  Ibicaré: 'Joaçaba',
  Içara: 'Criciúma',
  Ilhota: 'Blumenau',
  Imaruí: 'Laguna',
  Imbituba: 'Laguna',
  Imbuia: 'Ituporanga',
  Indaial: 'Timbó',
  Iomerê: 'Videira',
  Ipira: 'Concórdia',
  "Iporã do Oeste": 'Itapiranga',
  Itapiranga: 'Itapiranga',
  Ipuaçu: 'Xanxerê',
  Ipumirim: 'Seara',
  Iraceminha: 'Maravilha',
  Irani: 'Concórdia',
  Irati: 'Quilombo',
  Quilombo: 'Quilombo',
  Irineópolis: 'Canoinhas',
  Itá: 'Seara',
  Itaiópolis: 'Mafra',
  Itapema: 'Itajaí',
  Itapoá: 'Joinville',
  Jaborá: 'Joaçaba',
  'Jacinto Machado': 'Araranguá',
  Jaguaruna: 'Tubarão',
  Jardinópolis: 'Quilombo',
  'José Boiteux': 'Ibirama',
  Jupiá: "São Lourenço d'Oeste",
  Lacerdópolis: 'Joaçaba',
  'Lajeado Grande': 'Xanxerê',
  Laurentino: 'Rio do Sul',
  'Lauro Müller': 'Criciúma',
  'Lauro Muller': 'Criciúma',
  'Lebon Régis': 'Caçador',
  'Leoberto Leal': 'Ituporanga',
  'Lindóia do Sul': 'Seara',
  Lontras: 'Ibirama',
  'Luiz Alves': 'Blumenau',
  Luzerna: 'Joaçaba',
  Macieira: 'Caçador',
  'Major Gercino': 'Brusque',
  'Major Vieira': 'Canoinhas',
  Maracajá: 'Araranguá',
  Marema: 'Xanxerê',
  Massaranduba: 'Jaraguá do Sul',
  'Matos Costa': 'Caçador',
  Meleiro: 'Araranguá',
  'Mirim Doce': 'Taió',
  'Taió': 'Taió',
  Modelo: 'Maravilha',
  Mondai: 'Palmitos',
  'Mondaí': 'Palmitos',
  'Monte Carlo': 'Campos Novos',
  'Monte Castelo': 'Mafra',
  'Morro do Fumaça': 'Criciúma',
  'Morro da Fumaça': 'Criciúma',
  'Morro Grande': 'Araranguá',
  Navegantes: 'Itajaí',
  'Nova Erechim': 'Chapecó',
  'Nova Itaberaba': 'Chapecó',
  'Nova Trento': 'Brusque',
  'Nova Veneza': 'Criciúma',
  'Novo Horizonte': "São Lourenço d'Oeste",
  Orleans: 'Criciúma',
  'Otacílio Costa': 'Lages',
  Ouro: 'Joaçaba',
  'Ouro Verde': 'Xanxerê',
  Painel: 'Lages',
  Palhoça: 'Florianópolis',
  'Palma Sola': 'Dionísio Cerqueira',
  Palmeira: 'Lages',
  Papanduva: 'Mafra',
  Paraíso: "São Miguel d'Oeste",
  'Passo de Torres': 'Araranguá',
  'Passos Maia': 'Xanxerê',
  'Paulo Lopes': 'Laguna',
  'Pedras Grandes': 'Tubarão',
  Penha: 'Itajaí',
  Peritiba: 'Concórdia',
  'Pescaria Brava': 'Laguna',
  Petrolândia: 'Ituporanga',
  Pinhalzinho: 'Maravilha',
  'Pinheiro Preto': 'Videira',
  Piratuba: 'Concórdia',
  'Planalto Alegre': 'Chapecó',
  Pomerode: 'Blumenau',
  'Ponte Alta': 'Lages',
  'Ponte Alta do Norte': 'Curitibanos',
  'Ponte Serrada': 'Xanxerê',
  'Porto Belo': 'Itajaí',
  'Porto União': 'Canoinhas',
  'Pouso Redondo': 'Taió',
  'Praia Grande': 'Araranguá',
  Paial: 'Seara',
  'Presidente Castello Branco': 'Concórdia',
  'Presidente Getúlio': 'Ibirama',
  'Presidente Nereu': 'Ibirama',
  Princesa: 'Dionísio Cerqueira',
  'Rancho Queimado': 'Florianópolis',
  'Rio das Antas': 'Caçador',
  'Rio do Campo': 'Taió',
  'Rio do Oeste': 'Rio do Sul',
  'Rio dos Cedros': 'Timbó',
  'Rio Fortuna': 'Braço do Norte',
  'Rio Negrinho': 'Mafra',
  'Rio Rufino': 'São Joaquim',
  Riqueza: 'Palmitos',
  Rodeio: 'Timbó',
  Romelândia: 'Maravilha',
  Salete: 'Taió',
  Saltinho: 'Maravilha',
  'Salto Veloso': 'Videira',
  Sangão: 'Tubarão',
  'Santa Cecília': 'Curitibanos',
  'Santa Helena': 'Itapiranga',
  'Santa Rosa de Lima': 'Braço do Norte',
  'Santa Rosa do Sul': 'Araranguá',
  'Santa Terezinha': 'Taió',
  'Santa Terezinha do Progresso': 'Maravilha',
  'Santiago do Sul': 'Quilombo',
  'Santo Amaro da Imperatriz': 'Florianópolis',
  'São Bento do Sul': 'Mafra',
  'São Bernardino': "São Lourenço d'Oeste",
  'São Bonifácio': 'Florianópolis',
  'São Carlos': 'Palmitos',
  'São Cristóvão do Sul': 'Curitibanos',
  'São Cristovão do Sul': 'Curitibanos',
  'São Domingos': 'Xanxerê',
  'São Francisco do Sul': 'Joinville',
  'São João Batista': 'Brusque',
  'São João do Itaperiú': 'Joinville',
  'São João do Oeste': 'Itapiranga',
  'São João do Sul': 'Araranguá',
  'São José': 'Florianópolis',
  'São José do Cedro': 'Dionísio Cerqueira',
  'São José do Cerrito': 'Lages',
  'São Ludgero': 'Braço do Norte',
  'São Martinho': 'Braço do Norte',
  'São Miguel da Boa Vista': 'Maravilha',
  'São Pedro de Alcântara': 'Florianópolis',
  Saudades: 'Maravilha',
  Schroeder: 'Jaraguá do Sul',
  Seara: 'Seara',
  'Serra Alta': 'Maravilha',
  Siderópolis: 'Criciúma',
  Sombrio: 'Araranguá',
  'Sul Brasil': 'Maravilha',
  'Tangará': 'Videira',
  Tigrinhos: 'Maravilha',
  Tijucas: 'Brusque',
  'Timbé do Sul': 'Araranguá',
  'Timbó Grande': 'Caçador',
  'Três Barras': 'Canoinhas',
  Treviso: 'Criciúma',
  'Treze de Maio': 'Tubarão',
  'Treze Tílias': 'Joaçaba',
  'Trombudo Central': 'Rio do Sul',
  Tunápolis: 'Itapiranga',
  Turvo: 'Araranguá',
  'União do Oeste': 'Quilombo',
  Urubici: 'São Joaquim',
  Urupema: 'São Joaquim',
  Urussanga: 'Criciúma',
  Vargeão: 'Xanxerê',
  Vargem: 'Campos Novos',
  'Vargem Bonita': 'Joaçaba',
  'Vidal Ramos': 'Ituporanga',
  'Vitor Meirelles': 'Ibirama',
  'Vitor Meireles': 'Ibirama',
  Witmarsum: 'Ibirama',
  Xavantina: 'Seara',
  Xaxim: 'Xanxerê',
  Zortéa: 'Campos Novos'
};

const CRE_NAMES = Array.from(new Set(Object.values(MUNICIPALITY_CRE_MAP))).sort((a, b) =>
  a.localeCompare(b, 'pt-BR')
);

const CRE_NUMBERS = {
  "Araranguá": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 7,
    presencial: 0,
    online: 1
  },
  "Blumenau": {
    publicoEE: 2756,
    escolas: 46,
    escolasAEE: 26,
    estudantesAEE: 640,
    participantes: 222,
    presencial: 1,
    online: 3
  },
  "Braço do Norte": {
    publicoEE: 827,
    escolas: 21,
    escolasAEE: 12,
    estudantesAEE: 266,
    participantes: 315,
    presencial: 1,
    online: 2
  },
  "Brusque": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 37,
    presencial: 0,
    online: 2
  },
  "Campos Novos": {
    publicoEE: 530,
    escolas: 22,
    escolasAEE: 7,
    estudantesAEE: 106,
    participantes: 134,
    presencial: 1,
    online: 0
  },
  "Canoinhas": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Caçador": {
    publicoEE: 920,
    escolas: 25,
    escolasAEE: 15,
    estudantesAEE: 272,
    participantes: 198,
    presencial: 1,
    online: 1
  },
  "Chapecó": {
    publicoEE: 2003,
    escolas: 43,
    escolasAEE: 36,
    estudantesAEE: 894,
    participantes: 302,
    presencial: 1,
    online: 0
  },
  "Concórdia": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 5,
    presencial: 0,
    online: 0
  },
  "Criciúma": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Curitibanos": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Dionísio Cerqueira": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 5,
    presencial: 0,
    online: 1
  },
  "Florianópolis": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 131,
    presencial: 0,
    online: 14
  },
  "Ibirama": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 47,
    presencial: 0,
    online: 5
  },
  "Itajaí": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Itapiranga": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 17,
    presencial: 0,
    online: 2
  },
  "Ituporanga": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 11,
    presencial: 0,
    online: 2
  },
  "Jaraguá do Sul": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Joaçaba": {
    publicoEE: 444,
    escolas: 28,
    escolasAEE: 13,
    estudantesAEE: 181,
    participantes: 143,
    presencial: 1,
    online: 0
  },
  "Joinville": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Lages": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Laguna": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 23,
    presencial: 0,
    online: 2
  },
  "Mafra": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 7,
    presencial: 0,
    online: 3
  },
  "Maravilha": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Palmitos": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Quilombo": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Rio do Sul": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Seara": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 7,
    presencial: 0,
    online: 1
  },
  "São Joaquim": {
    publicoEE: 484,
    escolas: 16,
    escolasAEE: 6,
    estudantesAEE: 134,
    participantes: 175,
    presencial: 1,
    online: 4
  },
  "São Lourenço d'Oeste": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "São Miguel d'Oeste": {
    publicoEE: 423,
    escolas: 23,
    escolasAEE: 11,
    estudantesAEE: 129,
    participantes: 300,
    presencial: 1,
    online: 0
  },
  "Taió": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 0,
    presencial: 0,
    online: 0
  },
  "Timbó": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 11,
    presencial: 0,
    online: 2
  },
  "Tubarão": {
    publicoEE: 2050,
    escolas: 43,
    escolasAEE: 31,
    estudantesAEE: 655,
    participantes: 147,
    presencial: 1,
    online: 1
  },
  "Videira": {
    publicoEE: 536,
    escolas: 23,
    escolasAEE: 15,
    estudantesAEE: 202,
    participantes: 152,
    presencial: 1,
    online: 6
  },
  "Xanxerê": {
    publicoEE: 0,
    escolas: 0,
    escolasAEE: 0,
    estudantesAEE: 0,
    participantes: 13,
    presencial: 0,
    online: 1
  }
};

function generateDefaultCreData(names = CRE_NAMES) {
  return names.map((name, index) => {
    const row = CRE_NUMBERS[name] || {};
    const publicoEE = Number.isFinite(row.publicoEE) ? row.publicoEE : 400 + index * 15;
    const escolas = Number.isFinite(row.escolas) ? row.escolas : 45 + (index % 6) * 3;
    const escolasAEE = Number.isFinite(row.escolasAEE) ? row.escolasAEE : Math.max(10, escolas - 8 - (index % 4));
    const estudantesAEE = Number.isFinite(row.estudantesAEE) ? row.estudantesAEE : Math.round(publicoEE * 0.58) + (index % 10) * 6;
    const participantes = Number.isFinite(row.participantes) ? row.participantes : 120 + (index * 7) % 90;
    const presencial = Number.isFinite(row.presencial) ? row.presencial : 20 + (index % 5) * 5;
    const online = Number.isFinite(row.online) ? row.online : 15 + (index % 7) * 4;
    return {
      code: `CRE${String(index + 1).padStart(2, '0')}`,
      name: `CRE ${name}`,
      regionName: name,
      colorIndex: index,
      publicoEE,
      escolas,
      escolasAEE,
      estudantesAEE,
      participantes,
      presencial,
      online,
      hasAssessoria: (presencial + online) > 0
    };
  });
}

const DEFAULT_CRE_DATA = generateDefaultCreData();
